spring:
  application:
    name: spring-ai-mcp-client-shopping-cart
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        
        stdio:
          servers-configuration: classpath:mcp-servers.json

logging:
  level:
    root: INFO
