spring:
  application:
    name: spring-ai-mcp-client-shopping-cart
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        
        stdio:
          servers-configuration: classpath:mcp-servers.json
          enabled: true
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: qwen2.5:3b

logging:
  level:
    root: INFO
